# Generated by Django 5.0.4 on 2024-04-12 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0002_usersurvey_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresponse',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invitation.surveyanswer'),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invitation.surveyquestion'),
        ),
    ]
