# Generated by Django 5.0.4 on 2024-04-12 04:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0003_alter_surveyresponse_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersurvey',
            name='first_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(20), django.core.validators.DecimalValidator(0, 0)]),
        ),
        migrations.AlterField(
            model_name='usersurvey',
            name='last_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(20), django.core.validators.DecimalValidator(0, 0)]),
        ),
    ]
